name: Build and deploy

on: [push]

jobs:        
  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Use Node.js 12.7
        uses: actions/setup-node@v1
        with:
          version: 12.7

      - name: Build
        run: |
          npm install
          npm run build --if-present

      - name: Publish to Webserver
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: access793420076.webspace-data.io
          FTP_USERNAME: u98144824
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: build
          REMOTE_DIR: gallery
